name: AI PR Review (Claude)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl https://cursor.com/install -fsSL | bash

      - name: AI review with Claude 4.5
        id: review
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x scripts/ai-review.sh
          ./scripts/ai-review.sh "${{ github.event.pull_request.html_url }}"
          # crude gate: if comment contains "❌ Request changes", fail the job
          if grep -q "❌ Request changes" /tmp/review.txt; then
            echo "changes_requested=true" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "changes_requested=false" >> $GITHUB_OUTPUT
          fi

      - name: Approve & merge if clean
        if: ${{ steps.review.outputs.changes_requested == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
          gh pr merge  ${{ github.event.pull_request.number }} --squash --auto
